#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 15 21:16:40 2020

@author: yojeremijenko-conel
"""

import pandas as pd 
import geopandas as gpd
import folium
from matplotlib import pyplot as plt



df = pd.read_csv('objects.csv')

df.plot(kind="scatter", x='gpsLongitude', y='gpsLatitude',
    s=df['person'], label="population", cmap=plt.get_cmap("jet"),
    colorbar=True, alpha=0.4, figsize=(10,7),
)
plt.legend()
plt.show()